### ISSUE TITLE
Deutex mangles images with a height of >= 256 and transparency.

### ISSUE THREAD

**Issue by NickZ** [Doom-Utils/deutex#10]
Obsoive: http://imgur.com/a/M8Phw

Basically, what's happening is that it's not handling the tallpic format correctly. The correct post for whenever the current pixel of the column is y=254 is `254 + 0 + 0 + 0 + [number of transparent pixels inbetween previous post and the next] + [length of next post]`, or `254 + 0 + 0 + 0 + 255` if the rest of the column is transparent pixels.

Instead, what it's doing is just `254 + [length of next post]`. As you can see, this is why non-transparency pics don't get mangled.

**Comment by Voros2** [comment]
Does Deutex even have transparency support?

**Comment by Altazimuth** [comment]
I was never able to find SLADE's code for converting pngs to patches, but psxwadgen apparently uses that code, and seems to work fine. Bear in mind it converts it to an internal linear-buffer format prior to this. https://github.com/haleyjd/psxwadgen/blob/master/v_psx.cpp#L226-L390

**Comment by NickZ** [comment]
Yes, Deutex does have transparency support; that was pretty much the point of adding PNG support. 

SLADE definitely does this correctly; I was working from SLADE's source code to figure out what the error was, which is how I found that the posts weren't being created correctly.
