### ISSUE TITLE
Conditional path seperators?

### ISSUE THREAD

**Issue by Voros2** [Doom-Utils/deutex#40]
Unix-based and Windows systems usually have / and \ as the default path seperators. Would using something like [this](https://github.com/Voros2/deutex/commit/969274d3801ed7ec7a72aa3829c8383083969134) be considered a good way to set the default path seperators Deutex recognises? Is it even needed?

**Comment by chungy** [comment]
That's probably a good idea. I'll look into when that code is called and test it.

**Comment by chungy** [comment]
Looks like it's only used for WAD merging, but that's ok. I'll push the commit, thanks.
