### ISSUE TITLE
Enable code integration 

### ISSUE THREAD

**Issue by Voros2** [Doom-Utils/deutex#5]
It would be nice to have CI, such as Travis CI, in the repo. That way, contributors can easily check if their changes compile successfully, without having to compile the code themselves.

**Comment by chungy** [comment]
Added in 8d5c50d11d3fa185e18c26ac77a2f561a44f852f -- thanks!

**Comment by chungy** [comment]
Sadly I'm not sure this will actually stick around. Seems they don't support Ubuntu Xenial which would be required to build with libpng 1.6. It's detrimental and not worth downgrading our code for libpng 1.2.

**Comment by Voros2** [comment]
How about using other services such as Ebert, Semaphore etc.?
