### ISSUE TITLE
Configure script should check for a2x by default, but error if explicitly requested

### ISSUE THREAD

**Issue by vilhelmgray** [Doom-Utils/deutex#64]
If a user explicitly requests manpage generation, the configure script should report an error if the system is unable to perform the request -- otherwise the build will fail unexpectedly on machines that do not have **a2x**.

There are 3 possible scenarios:

- `./configure`
  Here the configure script should check for **a2x** and build the manpage if able. If not able, the configure script will automatically disable the manpage build without error.
- `./configure --disable-man`
  The user explicitly requests to bypass the manpage build so the configure script should disable it.
- `./configure --enable-man`
  The user explicitly requests to enable the manpage build so the configure script should report an error if the system is unable to perform the build.

**Comment by chungy** [comment]
I appreciate the verbosity, but I feel like this is too complicated for an obscure corner-case (see comment on the PR #65). I'm ok with `--enable-man` basically being a no-op.

**Comment by vilhelmgray** [comment]
One of the important reasons this is useful is that it follows the canonical convention of Autotools configure scripts -- that a build should not fail after a successful configuration.

On my distribution, it is common for users to batch install several packages via scripts that test the results of configure scripts to verify support for requested features and options; when a configure script reports an error, it's obvious to the user that a configuration setting is incorrect and should be changed.

If I package Deutex 5.2.1 as it is now, I'll end up with several users reporting build errors for Deutex under the belief that the Deutex Makefile is broken when it's that their system does not support manpage generation.

Fixing the behavior of `--enable-man` should resolve confusion for users of my distribution before I release the deutex 5.2.1 package, so that I avoid these sort of error reports.

**Comment by chungy** [comment]
Merged the PR, but I'll hold on making a new point release for now. Feel free to include the patch with your ebuild if you wish.
